mode = "closest" # What technique will be used to determine similar files
normalizeWords = false # Removes accent and diacritics
pairsToFind = 3 # How many closest pairs are returned

synonymCount = 5 # Change to zero to not consider synonyms
language = "en" # Will be used to understand context of said files

useAbsolutePaths = false # If selected the app will return the full path instead of relative one
